# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('avert', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('created', models.IntegerField()),
            ],
            options={
                'db_table': 'passport',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('passport_id', models.IntegerField(primary_key=True, serialize=False)),
                ('token_id', models.IntegerField()),
                ('expire_time', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('created', models.IntegerField()),
                ('version', models.IntegerField()),
            ],
        ),
    ]
